"""Uniform document previews for the Streamlit UI (DOCX, PPTX, PDF, XLSX).

Every format is parsed into the project's existing Document IR
(ragapp.documents.model.DocumentModel) and drawn by ONE renderer inside ONE
frame, so a .docx, .pptx and .pdf all look the same:

    header line  ->  [Reading | Original layout]  ->  bordered scrolling frame

"Reading" is the uniform themed view. "Original layout" is the faithful page
view (st.pdf): native for PDFs, and for DOCX/PPTX when LibreOffice is installed.

Public API:  render_document_preview(path, key="")   and   DOCUMENT_SUFFIXES
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
import tempfile
from collections import Counter
from pathlib import Path

import streamlit as st

from ragapp.documents.model import Block, DocumentModel

DOCUMENT_SUFFIXES = {".docx", ".pptx", ".pdf", ".xlsx"}
FRAME_HEIGHT = 640
MAX_PDF_PAGES = 300
MAX_SHEET_ROWS = 200
MAX_SHEET_COLS = 30
MAX_IMAGE_BYTES = 3 * 1024 * 1024
_BULLET = re.compile(r"^\s*(?:[\x00-\x1f\x7f•●▪◦‣▶►■□·\uf0b7\uf0a7\-–—*]|\d+[.)])\s+")
_GLYPH = re.compile(r"^[\x00-\x1f\x7f•●▪◦‣▶►■□·\uf0b7\uf0a7\-–—*]{1,2}$")


# ------------------------------------------------------------------ helpers
def _human(n: float) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024 or unit == "GB":
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024
    return f"{n} B"


def _split_lines(text: str) -> list[str]:
    """PowerPoint stores soft breaks as \\n / \\v inside one paragraph; Markdown
    collapses those, so every line must become its own block."""
    return [ln.strip() for ln in re.split(r"[\n\r\v\x0b]+", text or "") if ln.strip()]


def _text_blocks(text: str, level: int = 0) -> list[Block]:
    out = []
    for line in _split_lines(text):
        if _BULLET.match(line) or level > 0:
            out.append(Block("list_item", text=_BULLET.sub("", line), level=level))
        else:
            out.append(Block("paragraph", text=line))
    return out


# ------------------------------------------------------------------ parsers
def parse_pptx(path: Path) -> DocumentModel:
    from pptx import Presentation

    prs = Presentation(str(path))

    def walk(shapes):
        for sh in sorted(shapes, key=lambda s: ((s.top or 0), (s.left or 0))):
            if sh.shape_type == 6:  # group
                yield from walk(sh.shapes)
            else:
                yield sh

    blocks: list[Block] = []
    deck_title = ""
    for n, slide in enumerate(prs.slides, 1):
        shapes = list(walk(slide.shapes))
        title_shape = slide.shapes.title
        title = title_shape.text_frame.text.strip() if title_shape is not None and title_shape.has_text_frame else ""
        skip_id = title_shape.shape_id if title else None
        # Blank-layout slides (e.g. generated by the agent) have no title
        # placeholder: use the top-most short single-line text box instead.
        if not title:
            texts = [s for s in shapes if getattr(s, "has_text_frame", False) and s.has_text_frame and s.text_frame.text.strip()]
            if len(texts) > 1:
                first = texts[0].text_frame.text.strip()
                if len(_split_lines(first)) == 1 and len(first) <= 90:
                    title, skip_id = first, texts[0].shape_id
        deck_title = deck_title or title
        blocks.append(Block("page_break", metadata={"label": f"Slide {n}"}))
        if title:
            blocks.append(Block("heading", text=title, level=2))
        for sh in shapes:
            if skip_id is not None and sh.shape_id == skip_id:
                continue
            if getattr(sh, "has_text_frame", False) and sh.has_text_frame:
                for p in sh.text_frame.paragraphs:
                    blocks.extend(_text_blocks(p.text, level=p.level or 0))
            elif getattr(sh, "has_table", False) and sh.has_table:
                blocks.append(Block("table", rows=[[c.text for c in r.cells] for r in sh.table.rows]))
            elif sh.shape_type == 13:
                try:
                    if len(sh.image.blob) <= MAX_IMAGE_BYTES:
                        blocks.append(Block("image", metadata={"bytes": sh.image.blob}))
                except Exception:
                    pass
        if slide.has_notes_slide and slide.notes_slide.notes_text_frame is not None:
            note = slide.notes_slide.notes_text_frame.text.strip()
            if note:
                blocks.append(Block("callout", text="Notes: " + note))
    return DocumentModel(title=deck_title or path.stem, blocks=blocks,
                         metadata={"unit": "slides", "count": len(prs.slides)})


def _pdf_rows(page) -> list[dict]:
    """Group pypdf text pieces into visual rows (a row = several cells if the
    pieces sit on the same baseline with a wide gap, i.e. a table row)."""
    pieces: list[tuple[float, float, float, str, float]] = []

    def visitor(text, cm, tm, font_dict, font_size):
        t = (text or "").replace("\n", " ")
        if t.strip():
            scale = abs(tm[3] or 1) * abs(cm[3] or 1)
            pieces.append((cm[4] + tm[4] * cm[0], cm[5] + tm[5] * cm[3],
                           (font_size or 10) * scale, t, cm[5]))

    try:
        page.extract_text(visitor_text=visitor)
    except Exception:
        return []
    rows: list[dict] = []
    for x, y, size, text, cmy in pieces:
        if rows and abs(rows[-1]["y"] - y) < 0.5 * max(size, 1) and x >= rows[-1]["x"]:
            r = rows[-1]
            gap = x - (r["x"] + len(r["last"]) * r["size"] * 0.5)
            if gap > 1.5 * size:
                r["cells"].append(text)
            else:
                sep = " " if (gap > 0.12 * size and not text.startswith(" ") and not r["cells"][-1].endswith(" ")) else ""
                r["cells"][-1] += sep + text
            r.update(x=x, last=text, size=max(r["size"], size))
        else:
            rows.append({"y": y, "x": x, "size": size, "cells": [text], "last": text, "cmy": cmy})
    for r in rows:
        r["cells"] = [re.sub(r"\s+", " ", c).strip() for c in r["cells"] if c.strip()]
    return [r for r in rows if r["cells"]]


def parse_pdf(path: Path) -> DocumentModel | None:
    """Best-effort reading view of a PDF: headings from font size, bullets,
    tables (cells on one baseline), running page numbers/headers dropped.
    Returns None when the PDF has no text layer (scans)."""
    from pypdf import PdfReader

    reader = PdfReader(str(path))
    total = len(reader.pages)
    pages: list[list[dict]] = []
    for page in reader.pages[:MAX_PDF_PAGES]:
        height = float(page.mediabox.height)
        rows = _pdf_rows(page)
        # Running header/footer: short text in the outer margins of the page.
        rows = [r for r in rows
                if not ((r["y"] < 0.05 * height or r["y"] > 0.955 * height)
                        and sum(len(c) for c in r["cells"]) <= 60)]
        pages.append(rows)

    weights: Counter = Counter()
    for pg in pages:
        for r in pg:
            weights[round(r["size"], 1)] += sum(len(c) for c in r["cells"])
    if not weights:
        return None
    body = weights.most_common(1)[0][0]
    head_sizes = sorted({round(r["size"], 1) for pg in pages for r in pg
                         if len(r["cells"]) == 1 and r["size"] >= body * 1.18
                         and len(r["cells"][0]) <= 120}, reverse=True)
    level_of = {s: min(i + 1, 4) for i, s in enumerate(head_sizes)}

    blocks: list[Block] = []
    title = ""
    for pno, pg in enumerate(pages, 1):
        blocks.append(Block("page_break", metadata={"label": f"Page {pno}"}))
        # If the producer starts a new text block per paragraph (ReportLab) the
        # block origin tells us where paragraphs end; otherwise fall back to
        # "the previous line stopped short of the right margin".
        block_aware = len({round(r["cmy"], 1) for r in pg}) > 3
        body_lens = [len(r["cells"][0]) for r in pg
                     if len(r["cells"]) == 1 and abs(r["size"] - body) < 0.6]
        max_len = max(body_lens, default=0)
        para: list[str] = []
        table: list[list[str]] = []
        prev = None

        def flush():
            if para:
                blocks.append(Block("paragraph", text=" ".join(para)))
                para.clear()

        def flush_table():
            if len(table) >= 2:
                width = max(len(r) for r in table)
                blocks.append(Block("table", rows=[r + [""] * (width - len(r)) for r in table]))
            else:
                for r in table:
                    blocks.append(Block("paragraph", text=" ".join(r)))
            table.clear()

        for r in pg:
            cells, size = r["cells"], round(r["size"], 1)
            if len(cells) >= 2 and _GLYPH.match(cells[0]):          # "• text"
                flush(); flush_table()
                blocks.append(Block("list_item", text=" ".join(cells[1:])))
                prev = None
            elif len(cells) >= 2:                                    # table row
                flush()
                if table and len(table[-1]) != len(cells):
                    flush_table()
                table.append(cells)
                prev = None
            else:
                flush_table()
                text = cells[0]
                if size in level_of and len(text) <= 120:
                    flush()
                    blocks.append(Block("heading", text=text, level=level_of[size]))
                    title = title or text
                    prev = None
                elif _BULLET.match(text):
                    flush()
                    blocks.append(Block("list_item", text=_BULLET.sub("", text)))
                    prev = None
                else:
                    if para and prev is not None:
                        same_block = abs(prev["cmy"] - r["cmy"]) < 0.5
                        continues = same_block if block_aware else len(prev["cells"][0]) >= 0.8 * max_len
                        if not continues:
                            flush()
                    para.append(text)
                    prev = r
        flush(); flush_table()
    return DocumentModel(title=title or path.stem, blocks=blocks,
                         metadata={"unit": "pages", "count": total,
                                   "truncated": total > MAX_PDF_PAGES})


def parse_xlsx(path: Path) -> DocumentModel:
    from openpyxl import load_workbook

    wb = load_workbook(str(path), read_only=True, data_only=True)
    blocks: list[Block] = []
    for ws in wb.worksheets:
        blocks.append(Block("heading", text=ws.title, level=2))
        rows, truncated = [], False
        for i, row in enumerate(ws.iter_rows(values_only=True)):
            if i >= MAX_SHEET_ROWS:
                truncated = True
                break
            rows.append(["" if v is None else str(v) for v in row[:MAX_SHEET_COLS]])
        while rows and not any(rows[-1]):
            rows.pop()
        if rows:
            width = max(len(r) for r in rows)
            blocks.append(Block("table", rows=[r + [""] * (width - len(r)) for r in rows]))
        else:
            blocks.append(Block("paragraph", text="(empty sheet)"))
        if truncated:
            blocks.append(Block("callout", text=f"Showing the first {MAX_SHEET_ROWS} rows of this sheet."))
    return DocumentModel(title=path.stem, blocks=blocks,
                         metadata={"unit": "sheets", "count": len(wb.worksheets)})


def _parse_docx(path: Path) -> DocumentModel:
    from ragapp.documents.parser import parse_docx

    model = parse_docx(path)
    # Word paragraphs can also contain soft line breaks.
    fixed: list[Block] = []
    for b in model.blocks:
        if b.kind == "paragraph" and re.search(r"[\n\v]", b.text):
            fixed.extend(_text_blocks(b.text))
        else:
            fixed.append(b)
    model.blocks = fixed
    return model


@st.cache_data(show_spinner="Reading document…", max_entries=16)
def _load_model(path_str: str, mtime: float) -> DocumentModel | None:
    path = Path(path_str)
    suffix = path.suffix.lower()
    if suffix == ".docx":
        return _parse_docx(path)
    if suffix == ".pptx":
        return parse_pptx(path)
    if suffix == ".pdf":
        return parse_pdf(path)
    if suffix == ".xlsx":
        return parse_xlsx(path)
    return None


# ------------------------------------------------------------- block renderer
def _esc(text: str) -> str:
    return re.sub(r"([\\`*_{}\[\]<>$~|#])", r"\\\1", text)


def _table(rows: list[list[str]]) -> None:
    import pandas as pd

    if len(rows) < 2:
        st.table(rows)
        return
    seen: Counter = Counter()
    cols = []
    for i, name in enumerate(rows[0]):
        name = (name or "").strip() or f"col {i + 1}"
        seen[name] += 1
        cols.append(name if seen[name] == 1 else f"{name} ({seen[name]})")
    width = len(cols)
    body = [(r + [""] * width)[:width] for r in rows[1:]]
    st.table(pd.DataFrame(body, columns=cols))


def render_blocks(model: DocumentModel) -> None:
    for b in model.blocks:
        if b.kind == "heading":
            st.markdown("#" * max(1, min(b.level or 1, 6)) + " " + _esc(b.text))
        elif b.kind == "paragraph":
            st.markdown(_esc(b.text))
        elif b.kind == "list_item":
            indent = "    " * (b.level or 0)
            st.markdown(f"{indent}- {_esc(b.text)}")
        elif b.kind == "callout":
            st.info(b.text)
        elif b.kind == "table" and b.rows:
            _table(b.rows)
        elif b.kind == "image":
            st.image(b.metadata["bytes"])
        elif b.kind == "page_break":
            st.divider()
            if b.metadata.get("label"):
                st.caption(b.metadata["label"])


# ----------------------------------------------------------- original layout
def _soffice() -> str | None:
    found = shutil.which("soffice") or shutil.which("libreoffice")
    if found:
        return found
    for cand in (
        r"C:\Program Files\LibreOffice\program\soffice.exe",
        r"C:\Program Files (x86)\LibreOffice\program\soffice.exe",
        "/Applications/LibreOffice.app/Contents/MacOS/soffice",
    ):
        if os.path.exists(cand):
            return cand
    return None


@st.cache_data(show_spinner="Rendering pages…", max_entries=8)
def _office_to_pdf(path_str: str, mtime: float) -> bytes | None:
    exe = _soffice()
    if not exe:
        return None
    with tempfile.TemporaryDirectory(prefix="preview-") as tmp:
        try:
            subprocess.run([exe, "--headless", "--convert-to", "pdf", "--outdir", tmp, path_str],
                           check=True, capture_output=True, timeout=120)
        except Exception:
            return None
        out = Path(tmp) / (Path(path_str).stem + ".pdf")
        return out.read_bytes() if out.exists() else None


def _original_pdf_bytes(path: Path) -> bytes | None:
    if path.suffix.lower() == ".pdf":
        return path.read_bytes()
    if path.suffix.lower() in {".docx", ".pptx"}:
        return _office_to_pdf(str(path), path.stat().st_mtime)
    return None


# ------------------------------------------------------------------- public
def render_document_preview(path: Path, key: str = "") -> None:
    suffix = path.suffix.lower()
    try:
        stat = path.stat()
        model = _load_model(str(path), stat.st_mtime)
    except Exception as exc:
        st.error(f"Could not preview `{path.name}`: {exc}")
        return

    meta = (model.metadata if model else {}) or {}
    bits = [suffix.lstrip(".").upper(), _human(stat.st_size)]
    if meta.get("count"):
        n = meta["count"]; unit = meta.get("unit", ""); bits.append(f"{n} {unit[:-1] if n == 1 and unit.endswith('s') else unit}".strip())
    st.caption(" · ".join(bits))

    # Which views exist for this file?
    views = []
    if model is not None:
        views.append("Reading")
    if suffix == ".pdf" or (suffix in {".docx", ".pptx"} and _soffice()):
        views.append("Original layout")
    if not views:
        st.warning("No text could be extracted from this file (it may be a scan or image-only).")
        return
    if model is None and suffix == ".pdf":
        st.caption("No text layer found (scanned PDF) - showing the original pages.")
    view = views[0]
    if len(views) > 1:
        view = st.segmented_control("View", views, default=views[0],
                                    key=f"pv_view_{key}_{path}", label_visibility="collapsed") or views[0]

    if view == "Original layout":
        data = _original_pdf_bytes(path)
        if data is None:
            st.warning("Could not render the original layout for this file.")
            return
        try:
            st.pdf(data, height=FRAME_HEIGHT)
        except Exception as exc:  # e.g. streamlit-pdf not installed
            st.warning(f"PDF viewer unavailable ({exc}). Run `uv sync`, or use Download.")
        return

    if meta.get("truncated"):
        st.caption(f"Showing the first {MAX_PDF_PAGES} pages.")
    with st.container(height=FRAME_HEIGHT, border=True):
        if not model.blocks:
            st.info("This file contains no previewable content.")
        else:
            render_blocks(model)